"use client";
import { useState, useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle2, XCircle, Timer, ArrowRight, Brain, Info, LayoutDashboard, AlertTriangle } from 'lucide-react';
import axios from 'axios';
import Link from 'next/link';

const MISTAKE_TYPES = ['Conceptual', 'Factual Confusion', 'Silly Mistake', 'Guessing', 'Elimination Failure'];

export default function PracticeEngine() {
    const searchParams = useSearchParams();
    const [questions, setQuestions] = useState([]);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [selectedOption, setSelectedOption] = useState(null);
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [loading, setLoading] = useState(true);
    const [results, setResults] = useState({ correct: 0, wrong: 0 });
    const [showMistakeModal, setShowMistakeModal] = useState(false);
    const [timeLeft, setTimeLeft] = useState(45); // Working Timer

    useEffect(() => {
        const fetchQuestions = async () => {
            try {
                const userInfo = JSON.parse(localStorage.getItem('userInfo'));
                
                // Get filters from the URL generated by Practice Setup
                const subjects = searchParams.get('subjects');
                const topics = searchParams.get('topics');
                const years = searchParams.get('years');
                const limit = searchParams.get('limit') || userInfo?.dailyMcqTarget || 10;

                const { data } = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/api/questions/daily`, {
                    params: { limit, subjects, topics, years },
                    headers: { Authorization: `Bearer ${userInfo.token}` }
                });
                setQuestions(data);
            } catch (err) { 
                console.error("Fetch failed", err); 
            } finally { 
                setLoading(false); 
            }
        };
        fetchQuestions();
    }, [searchParams]);

    // TIMER LOGIC: Counts down every second
    useEffect(() => {
        if (loading || isSubmitted || currentIndex === 'finished' || questions.length === 0) return;

        if (timeLeft <= 0) {
            handleSubmitClick(); // Auto-submit if time runs out
            return;
        }

        const timer = setInterval(() => {
            setTimeLeft(prev => prev - 1);
        }, 1000);

        return () => clearInterval(timer);
    }, [timeLeft, isSubmitted, loading, currentIndex]);

    const handleAnswer = (label) => {
        if (isSubmitted) return;
        setSelectedOption(label);
    };

    const finalizeAnswer = async (mistakeCat = 'None') => {
        const currentQ = questions[currentIndex];
        const isCorrect = selectedOption === currentQ.correctOption;
        
        setIsSubmitted(true);
        setShowMistakeModal(false);

        try {
            const userInfo = JSON.parse(localStorage.getItem('userInfo'));
            await axios.post(`${process.env.NEXT_PUBLIC_API_URL}/api/attempts/log`, {
                questionId: currentQ._id,
                isCorrect,
                selectedOption,
                mistakeCategory: mistakeCat,
                timeTaken: 45 - timeLeft // Log actual time taken
            }, { headers: { Authorization: `Bearer ${userInfo.token}` } });

            if (isCorrect) {
                setResults(prev => ({ ...prev, correct: prev.correct + 1 }));
            } else {
                setResults(prev => ({ ...prev, wrong: prev.wrong + 1 }));
            }
        } catch (err) {
            console.error("Failed to log attempt", err);
        }
    };

    const handleSubmitClick = () => {
        if (!selectedOption) {
            // Handle case where time runs out without selection
            finalizeAnswer('Time Pressure');
            return;
        }
        const isCorrect = selectedOption === questions[currentIndex].correctOption;
        
        if (isCorrect) {
            finalizeAnswer('None');
        } else {
            setShowMistakeModal(true);
        }
    };

    const nextQuestion = () => {
        if (currentIndex < questions.length - 1) {
            setCurrentIndex(prev => prev + 1);
            setSelectedOption(null);
            setIsSubmitted(false);
            setTimeLeft(45); // Reset timer for the next question
        } else {
            setCurrentIndex('finished');
        }
    };

    if (loading) return (
        <div className="min-h-screen bg-brand-light flex items-center justify-center font-black animate-pulse uppercase tracking-widest text-brand-muted">
            Initializing PrepOS Engine...
        </div>
    );

    // STRICT CHECK: If no questions match the filters selected by user
    if (!loading && questions.length === 0) {
        return (
            <div className="min-h-screen bg-brand-light flex flex-col items-center justify-center p-6 text-center">
                <motion.div initial={{opacity:0, scale:0.95}} animate={{opacity:1, scale:1}} className="max-w-md bg-white p-10 rounded-[40px] shadow-premium border border-brand-border">
                    <div className="bg-orange-50 w-16 h-16 rounded-3xl flex items-center justify-center mx-auto mb-6 text-orange-500 border border-orange-100">
                        <Brain size={32} />
                    </div>
                    <h2 className="text-2xl font-black text-brand-dark mb-2 tracking-tight">No Questions Found</h2>
                    <p className="text-brand-muted font-medium mb-8 leading-relaxed text-sm">
                        There are no questions in our database for this specific combination of Year, Subject, and Topic.
                    </p>
                    <Link href="/practice/setup" className="block w-full bg-brand-dark text-white p-4 rounded-2xl font-bold hover:bg-brand-accent transition-all shadow-lg text-sm">
                        Adjust Search Filters
                    </Link>
                </motion.div>
            </div>
        );
    }

    if (currentIndex === 'finished') {
        return (
            <div className="min-h-screen bg-brand-light flex items-center justify-center p-6">
                <motion.div initial={{scale:0.9, opacity:0}} animate={{scale:1, opacity:1}} className="max-w-md w-full bg-white p-10 rounded-[40px] shadow-premium text-center border border-brand-border">
                    <h2 className="text-3xl font-black mb-2">Session Complete!</h2>
                    <p className="text-brand-muted font-medium mb-8">You've moved 1% closer to your goal.</p>
                    
                    <div className="grid grid-cols-2 gap-4 mb-8">
                        <div className="bg-green-50 p-6 rounded-3xl border border-green-100">
                            <p className="text-xs font-black text-status-success uppercase mb-1">Correct</p>
                            <p className="text-3xl font-black">{results.correct}</p>
                        </div>
                        <div className="bg-red-50 p-6 rounded-3xl border border-red-100">
                            <p className="text-xs font-black text-status-error uppercase mb-1">Incorrect</p>
                            <p className="text-3xl font-black">{results.wrong}</p>
                        </div>
                    </div>

                    <Link href="/dashboard" className="block w-full bg-brand-dark text-white p-4 rounded-2xl font-bold hover:bg-brand-accent transition-all shadow-lg">
                        Back to Dashboard
                    </Link>
                </motion.div>
            </div>
        );
    }

    const currentQ = questions[currentIndex];
    const progress = ((currentIndex + 1) / questions.length) * 100;

    return (
        <div className="min-h-screen bg-brand-light pb-20">
            {/* Top Header */}
            <div className="bg-white border-b border-brand-border p-4 sticky top-0 z-50">
                <div className="max-w-4xl mx-auto flex items-center justify-between px-2">
                    <Link href="/dashboard" className="text-brand-muted hover:text-brand-dark transition-all"><LayoutDashboard size={20}/></Link>
                    <div className="flex-1 mx-8 h-2 bg-brand-light rounded-full overflow-hidden border border-brand-border">
                        <motion.div animate={{width: `${progress}%`}} className="h-full bg-brand-accent shadow-[0_0_10px_rgba(99,102,241,0.4)]" />
                    </div>
                    <div className={`flex items-center gap-2 font-black text-xs transition-colors ${timeLeft < 10 ? 'text-status-error animate-pulse' : 'text-brand-muted'}`}>
                        <Timer size={16} /> 00:{timeLeft < 10 ? `0${timeLeft}` : timeLeft}
                    </div>
                </div>
            </div>

            <main className="max-w-3xl mx-auto p-6 mt-10">
                <AnimatePresence mode="wait">
                    <motion.div 
                        key={currentIndex}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -20 }}
                        className="space-y-8"
                    >
                        {/* Question Text */}
                        <div className="bg-white p-8 md:p-12 rounded-[40px] shadow-premium border border-brand-border">
                            <div className="flex items-center gap-2 mb-4 text-[10px] font-black text-brand-accent uppercase tracking-[0.2em]">
                                <Brain size={12}/> Question {currentIndex + 1} of {questions.length} • {currentQ.year}
                            </div>
                            <h2 className="text-xl md:text-2xl font-bold leading-relaxed text-brand-dark">
                                {currentQ.questionText}
                            </h2>
                        </div>

                        {/* Options */}
                        <div className="grid grid-cols-1 gap-4">
                            {currentQ.options.map((opt) => (
                                <button 
                                    key={opt.label}
                                    onClick={() => handleAnswer(opt.label)}
                                    className={`
                                        p-5 rounded-3xl text-left font-bold transition-all border-2 flex items-center justify-between group cursor-pointer
                                        ${selectedOption === opt.label ? 'border-brand-accent bg-indigo-50/30' : 'border-brand-border bg-white hover:border-brand-accent'}
                                        ${isSubmitted && opt.label === currentQ.correctOption ? '!border-status-success bg-green-50/50' : ''}
                                        ${isSubmitted && selectedOption === opt.label && selectedOption !== currentQ.correctOption ? '!border-status-error bg-red-50/50' : ''}
                                    `}
                                >
                                    <div className="flex items-center gap-4">
                                        <span className={`w-10 h-10 rounded-xl flex items-center justify-center border-2 transition-all
                                            ${selectedOption === opt.label ? 'bg-brand-accent text-white border-brand-accent' : 'bg-brand-light text-brand-muted border-brand-border group-hover:border-brand-accent'}
                                        `}>
                                            {opt.label}
                                        </span>
                                        <span className="text-brand-dark">{opt.text}</span>
                                    </div>
                                    {isSubmitted && opt.label === currentQ.correctOption && <CheckCircle2 className="text-status-success" />}
                                    {isSubmitted && selectedOption === opt.label && selectedOption !== currentQ.correctOption && <XCircle className="text-status-error" />}
                                </button>
                            ))}
                        </div>

                        {/* Bottom Actions / Explanation */}
                        {isSubmitted ? (
                            <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="space-y-6">
                                <div className="bg-brand-dark text-white p-8 rounded-[40px] shadow-xl">
                                    <h4 className="flex items-center gap-2 font-black text-xs uppercase tracking-widest mb-4 opacity-60">
                                        <Info size={14} /> Explanation
                                    </h4>
                                    <p className="text-sm font-medium leading-relaxed opacity-90">{currentQ.explanation}</p>
                                </div>
                                <button 
                                    onClick={nextQuestion}
                                    className="w-full bg-brand-accent text-white p-5 rounded-[24px] font-black shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-3"
                                >
                                    Continue <ArrowRight size={20} />
                                </button>
                            </motion.div>
                        ) : (
                            <button 
                                onClick={handleSubmitClick}
                                disabled={!selectedOption}
                                className="w-full bg-brand-dark text-white p-5 rounded-[24px] font-black shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-30 cursor-pointer"
                            >
                                Submit Answer
                            </button>
                        )}
                    </motion.div>
                </AnimatePresence>
            </main>

            {/* MISTAKE ANALYSIS MODAL */}
            <AnimatePresence>
                {showMistakeModal && (
                    <div className="fixed inset-0 bg-brand-dark/80 backdrop-blur-md z-[100] flex items-center justify-center p-6">
                        <motion.div 
                            initial={{y:50, opacity:0}} 
                            animate={{y:0, opacity:1}} 
                            exit={{y:50, opacity:0}} 
                            className="bg-white w-full max-w-md rounded-[40px] p-8 shadow-2xl border border-brand-border"
                        >
                            <div className="text-center mb-8">
                                <div className="bg-red-50 w-16 h-16 rounded-3xl flex items-center justify-center mx-auto mb-4 text-status-error border border-red-100">
                                    <AlertTriangle size={32}/>
                                </div>
                                <h3 className="text-2xl font-black text-brand-dark">Analyze Mistake</h3>
                                <p className="text-brand-muted text-sm font-medium mt-1 leading-relaxed">Be honest—it helps the analytics engine.</p>
                            </div>
                            <div className="grid grid-cols-1 gap-3">
                                {MISTAKE_TYPES.map(type => (
                                    <button 
                                        key={type} 
                                        onClick={() => finalizeAnswer(type)}
                                        className="p-4 bg-brand-light hover:bg-brand-accent hover:text-white rounded-2xl text-left font-bold text-sm transition-all cursor-pointer border border-brand-border"
                                    >
                                        {type}
                                    </button>
                                ))}
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
}